### PR TITLE
Improved css bundle support

### PR DESCRIPTION
**Pull request by vtrifonov**
Refactored webpack.config.js file for better **css/scss** support.

### CODE REVIEW

**Comment by rigor789** [comment]
Seems like `nativescript-dev-webpack` versions above `0.17.0-2018-09-27-191217-06` are missing the `style-hot-loader` and `apply-css-loader` files.

I'll wait before merging, to avoid issues due to the missing files.

**Comment by rigor789** [comment]
I also noticed that there is no way to remove css at runtime. If you delete a css property and the app syncs with hmr, the property will still affect the app.

Example:
```xml
<Label class="message"/>
```
```css
.message {
  font-size: 20;
  color: red;
}
```

If I remove `color: red;` the label stays red until I restart the tns commands. Changing it to `blue` does work though. Do you know where this could be implemented?

**Comment by vtrifonov** [comment]
> Seems like `nativescript-dev-webpack` versions above `0.17.0-2018-09-27-191217-06` are missing the `style-hot-loader` and `apply-css-loader` files.
> 
> I'll wait before merging, to avoid issues due to the missing files.

This happens because of the ^ in front, seems that it takes the version from RC which does not contain those loaders, so I'm using a concrete version now.

**Comment by sis0k0** [comment]
@vtrifonov, you can use the `next` tag as well.

**Comment by vtrifonov** [comment]
> I also noticed that there is no way to remove css at runtime. If you delete a css property and the app syncs with hmr, the property will still affect the app.
> 
> Example:
> 
> ```
> <Label class="message"/>
> ```
> 
> ```css
> .message {
>   font-size: 20;
>   color: red;
> }
> ```
> 
> If I remove `color: red;` the label stays red until I restart the tns commands. Changing it to `blue` does work though. Do you know where this could be implemented?

This seems like something that need to be implemented in the tns-core-modules, could you log an issue there about it?

**Comment by rigor789** [comment]
@vtrifonov thanks, will open an issue about the css unloading.

**Comment by rigor789** [comment]
https://github.com/NativeScript/NativeScript/issues/6320

**Pull request merged**
